import {
  ExceptionFilter,
  Catch,
  ArgumentsHost,
  HttpException,
  HttpStatus,
} from '@nestjs/common';
import { FastifyReply, FastifyRequest } from 'fastify';
import { QueryFailedError } from 'typeorm';

@Catch()
export class HttpExceptionFilter<T> implements ExceptionFilter {
  catch(exception: unknown, host: ArgumentsHost) {
    const ctx = host.switchToHttp();
    const response = ctx.getResponse<FastifyReply>(); // ‚úÖ Usar Fastify
    const request = ctx.getRequest<FastifyRequest>(); // ‚úÖ Usar Fastify

    let status = HttpStatus.INTERNAL_SERVER_ERROR; // Por defecto, error 500
    let message = 'Error interno del servidor';

    // üìå Imprimir el error en la consola para debug
    console.error('‚ùå ERROR DETECTADO:', exception);

    // ‚úÖ Capturar errores de PostgreSQL (TypeORM)
    if (exception instanceof QueryFailedError) {
      if ((exception as any).code === '23505') {
        status = HttpStatus.CONFLICT; // 409 Conflict
        message = (exception as any).detail; // üî• Extraer el detalle de la clave duplicada
      }
    }

    // ‚úÖ Capturar errores de NestJS
    else if (exception instanceof HttpException) {
      status = exception.getStatus();
      const exceptionResponse = exception.getResponse();

      // Extraer mensaje del error
      message =
        typeof exceptionResponse === 'string'
          ? exceptionResponse
          : (exceptionResponse as any).message || message;
    }

    // üìå Respuesta uniforme para el frontend
    response.status(status).send({
      statusCode: status,
      message,
      error: HttpStatus[status],
      timestamp: new Date().toISOString(),
      path: request.url,
    });
  }
}
